Replace CloudFront invalidation with API Gateway endpoint

diff --git a/.github/workflows/stable_repo.yaml b/.github/workflows/stable_repo.yaml
--- a/.github/workflows/stable_repo.yaml
+++ b/.github/workflows/stable_repo.yaml
@@ -39,11 +39,9 @@ jobs:
           mkdir s3dir
           aws s3 cp ${{ secrets.AWS_BUCKET_URL }}/charts/stable/ ./s3dir  --recursive
           aws s3 cp ./s3dir ${{ secrets.AWS_BUCKET_URL }}/charts/stable --acl public-read --recursive
-      - name: Purge download CDN
+      - name: Invalidate cache
         run: |
-          aws apigateway test-invoke-method \
-            --rest-api-id ${{ secrets.AWS_API_REST_ID }} \
-            --resource-id ${{ secrets.AWS_API_RESOURCE_ID }} \
-            --http-method PUT \
-            --path-with-query-string "/prod/download-oo-com" \
-            --body '{"paths": ["/charts/stable/*"]}'
+          API_STATUS=$(aws apigateway test-invoke-method --rest-api-id ${{ secrets.AWS_REST_API_ID }} --resource-id "${{ secrets.AWS_RESOURCE_ID }}" \
+            --http-method PUT --path-with-query-string "/prod/download-oo-com" --body "$(jq -c -n '.paths = $ARGS.positional' --args "/charts/stable/*")" \
+            --region us-east-1 --query 'status' --output text || :)
+          echo "API Gateway test-invoke status: ${API_STATUS:-<failed>}"
